config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :kittens
  root to: 'kittens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html 
      format.json { render json: @kittens }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    @kitten.save

    flash[:notice] = 'Kitten added to list'
    redirect_to kitten_path(@kitten)
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    @kitten.update(kitten_params)

    flash[:notice] = 'Kitten info updated'
    redirect_to kitten_path(@kitten)
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html 
      format.json { render json: @kitten }
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    flash[:notice] = 'Kitten removed from list'
    redirect_to kittens_path
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |f| %>
  <%= f.label :name %><br/>
  <%= f.text_field :name, required: true %><br/>
  <%= f.label :age %><br/>
  <%= f.text_field :age, required: true %><br/>
  <%= f.label :cuteness %><br/>
  <%= f.text_field :cuteness, required: true %><br/>
  <%= f.label :softness %><br/>
  <%= f.text_field :softness, required: true %><br/>
  <%= f.submit %>
<% end %>

app/views/kittens/edit.html.erb
<h2>Update a Kitten!</h2>

<%= render partial: 'form' %>
<%= link_to 'Back', kitten_path(@kitten.id) %>
<%= link_to 'Remove Kitten', kitten_path(@kitten), method: 'delete', data: {confirm: 'Remove kitten from list?'}  %><br/>

app/views/kittens/index.html.erb
<h2>Kitten List</h2> 
<%= link_to 'Add a new kitten', new_kitten_path %>

<ul>
  <% @kittens.each do |kitten| %>
    <li>
      <%= link_to kitten.name, kitten_path(kitten.id) %>, 
      <%= link_to 'Remove', kitten_path(kitten), method: 'delete', data: {confirm: 'Remove kitten from list?'} %>
    </li>
  <% end %>
</ul> 

app/views/kittens/new.html.erb
<h2>Add a Kitten!</h2>

<%= render partial: 'form' %>
<%= link_to 'Back', kittens_path %>

app/views/kittens/show.html.erb
<h2>Your Kitten</h2>
<div>
  <div>Name: <%= @kitten.name%></div>
  <div>Age: <%= @kitten.age%></div>
  <div>Cuteness: <%= @kitten.cuteness%></div>
  <div>Softness: <%= @kitten.softness%></div>
<div>
<%= link_to 'Update Info', edit_kitten_path(@kitten) %>
<%= link_to 'Remove Kitten', kitten_path(@kitten), method: 'delete', data: {confirm: 'Remove kitten from list?'}  %><br/>
<%= link_to 'Back', kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TOPRailsOdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>